name: Build Jamvox Debian Package

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PACKAGE_NAME: jamvox-driver-dkms
  PACKAGE_VERSION: 1.0.0

jobs:
  build-matrix:
    name: Build for Multiple Kernels
    strategy:
      matrix:
        ubuntu: ['20.04', '22.04', '24.04']
    runs-on: ubuntu-${{ matrix.ubuntu }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debhelper \
            devscripts \
            dh-dkms \
            dkms \
            build-essential \
            linux-headers-$(uname -r) \
            fakeroot
      
      - name: Build package
        run: |
          dpkg-buildpackage -us -uc -b
      
      - name: Upload package for Ubuntu ${{ matrix.ubuntu }}
        uses: actions/upload-artifact@v4
        with:
          name: package-ubuntu-${{ matrix.ubuntu }}
          path: ../*.deb
          retention-days: 30
