name: Build Jamvox Debian Package

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PACKAGE_NAME: jamvox-driver-dkms
  PACKAGE_VERSION: 1.0.0

jobs:
  build:
    name: Build Debian Package
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debhelper \
            devscripts \
            dkms \
            dh-dkms \
            build-essential \
            linux-headers-$(uname -r) \
            fakeroot \
            lintian \
            dpkg-dev
      
      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "PACKAGE_VERSION=$TAG_VERSION" >> $GITHUB_ENV
          
      - name: Update changelog
        run: |
          cd debian
          DEBFULLNAME="Jamvox Driver Team" \
          DEBEMAIL="driver@example.com" \
          dch -v ${PACKAGE_VERSION}-1 "Automated build from CI" || true
      
      - name: Build package
        run: |
          dpkg-buildpackage -us -uc -b
          
      - name: Run lintian
        run: |
          lintian ../${PACKAGE_NAME}_${PACKAGE_VERSION}-1_all.deb || true
          
      - name: List generated files
        run: |
          ls -lah ../*.deb ../*.buildinfo ../*.changes || true
      
      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}-1_all
          path: |
            ../*.deb
            ../*.buildinfo
            ../*.changes
          retention-days: 30
      
      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            ../*.build
            debian/*.debhelper.log
          retention-days: 7

  test:
    name: Test Package Installation
    needs: build
    runs-on: ubuntu-22.04
    
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}-1_all
      
      - name: Install package
        run: |
          sudo apt-get update
          sudo apt-get install -y dkms linux-headers-$(uname -r)
          sudo dpkg -i *.deb || sudo apt-get install -f -y
      
      - name: Verify installation
        run: |
          dpkg -l | grep jamvox
          ls -la /usr/src/jamvox-* || echo "Source not found"
          ls -la /etc/modprobe.d/jamvox.conf || echo "Config not found"
          ls -la /etc/udev/rules.d/99-jamvox.rules || echo "Udev rules not found"
      
      - name: Check DKMS status
        run: |
          sudo dkms status || echo "No DKMS modules found"

  release:
    name: Create GitHub Release
    needs: [build, test]
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}-1_all
      
      - name: Extract version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Generate release notes
        id: release_notes
        run: |
          cat > release_notes.md << 'EOF'
          ## Jamvox Driver v${{ steps.version.outputs.version }}
          
          ### Installation
          
          Download the `.deb` package and install:
          ```bash
          sudo dpkg -i jamvox-driver-dkms_${{ steps.version.outputs.version }}-1_all.deb
          sudo apt-get install -f
          ```
          
          ### Verify Installation
          ```bash
          # Check if driver is installed
          dkms status
          
          # Load the driver
          sudo modprobe jamvox
          
          # Verify device is recognized
          cat /proc/asound/cards
          ```
          
          ### What's Included
          - Kernel driver for VOX Jamvox USB audio interface
          - DKMS support for automatic rebuilding
          - ALSA configuration
          - Udev rules for device permissions
          
          ### Requirements
          - Ubuntu 22.04 or compatible Debian-based distribution
          - Kernel 5.15 or newer
          - DKMS package installed
          
          ### Supported Hardware
          - VOX Jamvox USB Audio Interface (VID: 0x0944, PID: 0x0117)
          EOF
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *.changes
            *.buildinfo
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-matrix:
    name: Build for Multiple Kernels
    strategy:
      matrix:
        ubuntu: ['20.04', '22.04', '24.04']
    runs-on: ubuntu-${{ matrix.ubuntu }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debhelper \
            devscripts \
            dkms \
            build-essential \
            linux-headers-$(uname -r) \
            fakeroot
      
      - name: Build package
        run: |
          dpkg-buildpackage -us -uc -b
      
      - name: Upload package for Ubuntu ${{ matrix.ubuntu }}
        uses: actions/upload-artifact@v4
        with:
          name: package-ubuntu-${{ matrix.ubuntu }}
          path: ../*.deb
          retention-days: 30
